sudo: required
dist: trusty
group: deprecated-2017Q4
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check -qq
script:
- source ./env.sh
- "${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}"
- "${DLR} ${FRTCP_URL} -o ${FRTCP_FN}"
- "${DLR} ${LNCR_URL} -o ${LNCR_ZIP}"
- 
- unzip ${LNCR_ZIP} ${LNCR_FN}
- sudo tar -zxpf ${ROOTFS_FN}
- cd root.x86_64
- sudo cp -f ../profile ./etc/profile
- sudo cp -bf ../mirrorlist ./etc/pacman.d/mirrorlist
- sudo cp -bf ../pacman.conf.nosig ./etc/pacman.conf
- sudo sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" ./etc/locale.gen
- echo "LANG=en_US.UTF-8" | sudo tee ./etc/locale.conf
- sudo cp -f ../${FRTCP_FN} ./root/
- sudo cp -f /etc/resolv.conf ./etc/resolv.conf
- sudo mv -f ./etc/mtab ./etc/mtab.bak
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- 
- sudo mount -t proc proc proc/
- sudo mount --bind /sys sys
- 
- sudo chroot . /usr/bin/pacman -Syu --noconfirm ${PAC_PKGS}
- sudo chmod u+s ./usr/bin/ping
- sudo rm -rf ./etc/mtab
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- sudo chroot . /usr/bin/locale-gen
- yes | sudo chroot . /usr/bin/pacman -U --force /root/${FRTCP_FN}
- yes | sudo chroot . /usr/bin/pacman -Scc
- 
- sudo umount ./{sys,proc}
- sudo mv -f ./etc/mtab.bak ./etc/mtab
- sudo cp -f ../pacman.conf ./etc/pacman.conf
- echo "# This file was automatically generated by WSL. To stop automatic generation
  of this file, remove this line." | sudo tee ./etc/resolv.conf
- 
- sudo rm -rf ./root/*
- 
- sudo tar -zcpf ../rootfs.tar.gz *
- sudo chown `id -un` ../rootfs.tar.gz
- cd ..
- 
- mkdir out
- mv -f ${LNCR_FN} ./out/
- mv -f rootfs.tar.gz ./out/
- cd out
- zip Arch.zip *
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: CbRtzFkfb4s7D1QkoOGZ1EL3Tb25J8oDJaThOGtu0NmKJVHcGLfeGzFo26ZCmgWWOldq7cqPv4XPzeikOKFADuuK5T3r2xyrD2NW86UXpGJdaqZQ9nQacOfENjfhgVqXMG8Rgzp2vVj7k8cR5Teyatyw4k1Q5MxQdTV8hUZanl/17T3nSR+ae+XOd5Tb/vf9R8IBWK9LIypXx8j3eDRXSvKhaHMHzHS74cMYz092YEWHIX6etx2YyHIPQDY1ZX5l18HmpDg6TGSYcgohEKrxJBZBkdEwxUnUXAb/K2+cwKHcr3SNvf0lB+WeDu1jSq+jznZWm9cfL/uVoy5FnHoZCeCNsX0nwTIGkeSvf/30DQyr4USn8uXGO4QXE8UwUUWwVs/5Ah8MVOX7OG8MIS8YteDIUSV/iRJyJilGQJ9bSB/xbFdywaMcBtaXZicU4Di5mrn62vdzRWkqsUiGtFoLr4mTvdcuvr/37OGUbb9LgVyb7WEdnRzoT9IpSJ2Ifs7ObW7woHHN8JzBdqrndBfxQfwt39kjVhauIadILPVDLNaQOZxTRVXE9VOcNEdxEGaKTYLbXDmmZO49/U8XI4HAjae3HbIyOcJlIjbXA6fJWEl8wOGm2vaRIMxXqr9PrC6PHdcR+B5R9MJE6Li/YJwT6Kan5XkA5ZYDz3YUITyFHYI=
  file: out/Arch.zip
  on:
    repo: yuk7/ArchWSL
    tags: true
    all_branches: true
skip_cleanup: true
