sudo: required
dist: trusty
group: deprecated-2017Q4
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check -qq
script:
- source ./env.sh
- "${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}"
- "${DLR} ${LNCR_URL} -o ${LNCR_ZIP}"
- 
- unzip ${LNCR_ZIP} ${LNCR_FN}
- mkdir out
- mv -f ${LNCR_FN} ./out/
- mv -f rootfs.tar.gz ./out/
- cd out
- zip Arch.zip *
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: CbRtzFkfb4s7D1QkoOGZ1EL3Tb25J8oDJaThOGtu0NmKJVHcGLfeGzFo26ZCmgWWOldq7cqPv4XPzeikOKFADuuK5T3r2xyrD2NW86UXpGJdaqZQ9nQacOfENjfhgVqXMG8Rgzp2vVj7k8cR5Teyatyw4k1Q5MxQdTV8hUZanl/17T3nSR+ae+XOd5Tb/vf9R8IBWK9LIypXx8j3eDRXSvKhaHMHzHS74cMYz092YEWHIX6etx2YyHIPQDY1ZX5l18HmpDg6TGSYcgohEKrxJBZBkdEwxUnUXAb/K2+cwKHcr3SNvf0lB+WeDu1jSq+jznZWm9cfL/uVoy5FnHoZCeCNsX0nwTIGkeSvf/30DQyr4USn8uXGO4QXE8UwUUWwVs/5Ah8MVOX7OG8MIS8YteDIUSV/iRJyJilGQJ9bSB/xbFdywaMcBtaXZicU4Di5mrn62vdzRWkqsUiGtFoLr4mTvdcuvr/37OGUbb9LgVyb7WEdnRzoT9IpSJ2Ifs7ObW7woHHN8JzBdqrndBfxQfwt39kjVhauIadILPVDLNaQOZxTRVXE9VOcNEdxEGaKTYLbXDmmZO49/U8XI4HAjae3HbIyOcJlIjbXA6fJWEl8wOGm2vaRIMxXqr9PrC6PHdcR+B5R9MJE6Li/YJwT6Kan5XkA5ZYDz3YUITyFHYI=
  file: out/Arch.zip
  on:
    repo: yuk7/ArchWSL
    tags: true
    all_branches: true
skip_cleanup: true
